// lib/email-builder.js
// Builds full HTML emails from processed data + Claude narratives
// ALL styles fully inline. No <style> blocks. No class= or id= attributes.
// Handles both Meta+TikTok and Meta-only campaigns

const F = "'Helvetica Neue',Helvetica,Arial,sans-serif";
function n(v) { return Number(v||0).toLocaleString('en-ZA'); }
function r(v) { return 'R'+Number(v||0).toLocaleString('en-ZA',{minimumFractionDigits:2,maximumFractionDigits:2}); }
function r0(v) { return 'R'+Number(v||0).toLocaleString('en-ZA',{minimumFractionDigits:0,maximumFractionDigits:0}); }
function pct(v) { return Number(v||0).toFixed(2)+'%'; }
function pct1(v) { return Number(v||0).toFixed(1)+'%'; }
function monthYear() { const d=new Date(); return ['January','February','March','April','May','June','July','August','September','October','November','December'][d.getMonth()]+' '+d.getFullYear(); }
function todayStr() { return new Date().toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'}); }

// ============ CLIENT EMAIL ============

function buildClientEmail(data, narratives) {
  const { meta, tiktok, hasTikTok, combined, community, dateRange } = data;
  const daysLeft = combined.totalDays - combined.daysElapsed;
  const fb = meta.facebook, ig = meta.instagram, kpis = meta.kpis;
  const platformBadges = hasTikTok
    ? `<td style="background:#1877F2;border-radius:5px;padding:5px 14px;"><span style="font-size:10px;font-weight:800;color:#fff;font-family:${F};">Facebook</span></td><td width="8"></td><td style="background:linear-gradient(135deg,#e1306c,#833ab4);border-radius:5px;padding:5px 14px;"><span style="font-size:10px;font-weight:800;color:#fff;font-family:${F};">Instagram</span></td><td width="8"></td><td style="background:#1e1e2e;border:1px solid #555577;border-radius:5px;padding:5px 14px;"><span style="font-size:10px;font-weight:800;color:#fff;font-family:${F};">TikTok</span></td>`
    : `<td style="background:#1877F2;border-radius:5px;padding:5px 14px;"><span style="font-size:10px;font-weight:800;color:#fff;font-family:${F};">Facebook</span></td><td width="8"></td><td style="background:linear-gradient(135deg,#e1306c,#833ab4);border-radius:5px;padding:5px 14px;"><span style="font-size:10px;font-weight:800;color:#fff;font-family:${F};">Instagram</span></td>`;
  const platformCount = hasTikTok ? '3 Platforms' : '2 Platforms';

  // TikTok section (only if has TikTok)
  const ttSection = hasTikTok ? buildTikTokClientSection(tiktok, combined, narratives.tiktokRead) : '';

  // Insights
  const insightCards = (narratives.insights||[]).map(i =>
    `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin-bottom:12px;border:1px solid rgba(255,255,255,0.15);border-radius:8px;border-left:4px solid #FFCB05;"><tr><td style="padding:18px 20px;"><p style="margin:0 0 7px;font-size:13px;font-weight:800;color:#fff;font-family:${F};">${i.title}</p><p style="margin:0;font-size:13px;color:rgba(255,255,255,0.90);line-height:1.78;font-family:${F};">${i.body}</p></td></tr></table>`
  ).join('');

  return `<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/></head>
<body style="margin:0;padding:0;background-color:#e8eff4;"><table role="presentation" border="0" cellpadding="0" cellspacing="0" width="100%" style="background-color:#e8eff4;"><tr><td align="center" style="padding:28px 16px 48px;"><table role="presentation" border="0" cellpadding="0" cellspacing="0" width="700" style="max-width:700px;width:100%;background-color:#ffffff;border-radius:12px;overflow:hidden;border:1px solid #d8e6ef;">
<tr><td style="background:#fff;padding:14px 32px;border-bottom:1px solid #e8e8e8;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td><span style="display:inline-block;width:30px;height:30px;background:linear-gradient(135deg,#E8231A,#FF7A00);border-radius:50%;text-align:center;line-height:30px;font-size:10px;font-weight:900;color:#fff;vertical-align:middle;font-family:${F};">GAS</span><span style="font-size:11px;font-weight:700;color:#1a1a1a;letter-spacing:1.5px;text-transform:uppercase;vertical-align:middle;margin-left:10px;font-family:${F};">GAS Marketing Automation</span></td><td align="right" style="font-size:9px;color:#999;letter-spacing:2px;text-transform:uppercase;font-family:${F};">Digital Performance Report</td></tr></table></td></tr>
<tr><td style="background:#004F71;padding:52px 44px 44px;"><p style="margin:0 0 10px;font-size:10px;font-weight:700;letter-spacing:5px;text-transform:uppercase;color:rgba(255,203,5,0.60);font-family:${F};">Paid Social &middot; Campaign Insights Report &middot; ${monthYear()}</p><h1 style="margin:0 0 4px;font-size:54px;font-weight:900;color:#FFCB05;line-height:1;letter-spacing:-2px;font-family:${F};">MTN MoMo</h1><p style="margin:0 0 24px;font-size:16px;font-weight:300;color:rgba(255,255,255,0.65);font-family:${F};">Campaign Performance and Audience Insights, ${dateRange.from} to ${dateRange.to}</p><table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin-bottom:22px;"><tr>${platformBadges}</tr></table></td></tr>
<tr><td style="background:#FFCB05;height:5px;font-size:1px;line-height:1px;">&nbsp;</td></tr>
<tr><td style="background:#fff;border-bottom:1px solid #d8e6ef;padding:36px 44px 28px;"><p style="margin:0 0 14px;font-size:15px;color:#1a1a1a;line-height:1.75;font-family:${F};">Dear <strong>MTN MoMo Team</strong>,</p><p style="margin:0;font-size:14px;color:#2d2d2d;line-height:1.85;font-family:${F};">Your paid social campaign for ${monthYear()} is running across ${platformCount.replace(' Platforms','')} platforms. This report covers performance through <strong>${dateRange.to}</strong>. The campaign has consumed <strong style="color:#004F71;">${pct1(combined.pacing)} of the ${r0(combined.budget)} budget</strong> with ${daysLeft} days remaining.</p></td></tr>
<tr><td style="background:#f0f6fb;border-bottom:1px solid #d8e6ef;padding:36px 44px 32px;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:0 0 22px;"><tr><td style="background:#1877F2;padding:14px 24px;border-radius:8px;"><span style="font-size:14px;font-weight:800;color:#fff;font-family:${F};">Facebook &nbsp;&middot;&nbsp; Campaign Performance</span></td></tr></table><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#fff;border:1px solid #d8e6ef;border-radius:10px;margin-bottom:18px;"><tr><td style="padding:22px;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0"><tr valign="top"><td width="24%" style="border-right:1px solid #d8e6ef;padding-right:14px;"><p style="margin:0 0 2px;font-size:9px;letter-spacing:2px;text-transform:uppercase;color:#999;font-family:${F};">Impressions</p><p style="margin:0;font-size:24px;font-weight:900;color:#1877F2;line-height:1;font-family:${F};">${n(fb.impressions)}</p></td><td width="4%"></td><td width="24%" style="border-right:1px solid #d8e6ef;padding:0 14px;"><p style="margin:0 0 2px;font-size:9px;letter-spacing:2px;text-transform:uppercase;color:#999;font-family:${F};">Spend / CPM</p><p style="margin:0;font-size:18px;font-weight:900;color:#004F71;font-family:${F};">${r0(fb.spend)}</p><p style="margin:4px 0 0;font-size:16px;font-weight:700;color:#2d2d2d;font-family:${F};">${r(fb.cpm)}</p></td><td width="4%"></td><td width="24%" style="padding-left:14px;"><p style="margin:0 0 2px;font-size:9px;letter-spacing:2px;text-transform:uppercase;color:#999;font-family:${F};">CTR / CPC</p><p style="margin:0;font-size:18px;font-weight:900;color:#1a7a3a;font-family:${F};">${pct(fb.ctr)}</p><p style="margin:4px 0 0;font-size:16px;font-weight:700;color:#1a7a3a;font-family:${F};">${r(fb.cpc)}</p></td></tr></table></td></tr></table><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#f0f6fb;border-left:4px solid #004F71;border-radius:0 8px 8px 0;margin-top:16px;"><tr><td style="padding:14px 18px;"><p style="margin:0 0 5px;font-size:11px;font-weight:800;color:#004F71;font-family:${F};">Facebook Campaign Read</p><p style="margin:0;font-size:13px;color:#2d2d2d;line-height:1.78;font-family:${F};">${narratives.facebookRead}</p></td></tr></table></td></tr>
<tr><td style="background:#fff;border-bottom:1px solid #d8e6ef;padding:36px 44px 32px;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:0 0 22px;"><tr><td style="background:linear-gradient(135deg,#e1306c,#833ab4);padding:14px 24px;border-radius:8px;"><span style="font-size:14px;font-weight:800;color:#fff;font-family:${F};">Instagram &nbsp;&middot;&nbsp; Campaign Performance</span></td></tr></table><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#fff;border:1px solid #d8e6ef;border-radius:10px;margin-bottom:18px;"><tr><td style="padding:22px;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0"><tr valign="top"><td width="24%" style="border-right:1px solid #d8e6ef;padding-right:14px;"><p style="margin:0 0 2px;font-size:9px;letter-spacing:2px;text-transform:uppercase;color:#999;font-family:${F};">Impressions</p><p style="margin:0;font-size:24px;font-weight:900;color:#833ab4;line-height:1;font-family:${F};">${n(ig.impressions)}</p></td><td width="4%"></td><td width="24%" style="border-right:1px solid #d8e6ef;padding:0 14px;"><p style="margin:0 0 2px;font-size:9px;letter-spacing:2px;text-transform:uppercase;color:#999;font-family:${F};">CPM</p><p style="margin:0;font-size:18px;font-weight:700;color:#1a7a3a;font-family:${F};">${r(ig.cpm)}</p></td><td width="4%"></td><td width="24%" style="padding-left:14px;"><p style="margin:0 0 2px;font-size:9px;letter-spacing:2px;text-transform:uppercase;color:#999;font-family:${F};">Spend</p><p style="margin:0;font-size:18px;font-weight:900;color:#004F71;font-family:${F};">${r0(ig.spend)}</p></td></tr></table></td></tr></table><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#f0f6fb;border-left:4px solid #004F71;border-radius:0 8px 8px 0;margin-top:16px;"><tr><td style="padding:14px 18px;"><p style="margin:0 0 5px;font-size:11px;font-weight:800;color:#004F71;font-family:${F};">Instagram Campaign Read</p><p style="margin:0;font-size:13px;color:#2d2d2d;line-height:1.78;font-family:${F};">${narratives.instagramRead}</p></td></tr></table></td></tr>
${ttSection}
<tr><td style="background:#004F71;padding:40px 44px;"><p style="margin:0 0 20px;font-size:10px;font-weight:800;letter-spacing:4px;text-transform:uppercase;color:rgba(255,255,255,0.50);font-family:${F};">Key Campaign Insights &nbsp;&middot;&nbsp; ${dateRange.from} to ${dateRange.to}</p>${insightCards}</td></tr>
<tr><td style="background:#fff;border-top:5px solid #FFCB05;padding:36px 44px 32px;"><p style="margin:0 0 20px;font-size:14px;color:#2d2d2d;line-height:1.85;font-family:${F};">${narratives.combinedRead}</p><p style="margin:0;font-size:14px;color:#1a1a1a;line-height:1.9;">Kind regards,<br/><strong style="color:#004F71;">SAMI</strong><br/><span style="font-size:12px;color:#555;">Head of AI Agents Team</span><br/><span style="font-size:12px;color:#555;">GAS Marketing Automation</span><br/><a href="http://www.gasmarketing.co.za" style="font-size:12px;color:#004F71;text-decoration:none;">www.gasmarketing.co.za</a><br/><a href="mailto:grow@gasmarketing.co.za" style="font-size:12px;color:#004F71;text-decoration:none;">grow@gasmarketing.co.za</a></p></td></tr>
<tr><td style="background:#1e1e2e;border-radius:0 0 12px 12px;padding:20px 44px;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td><span style="font-size:11px;color:rgba(255,255,255,0.45);">GAS Marketing Automation &nbsp;|&nbsp; Digital Performance Team &nbsp;|&nbsp;</span><a href="mailto:grow@gasmarketing.co.za" style="font-size:11px;color:#FF7A00;text-decoration:none;">grow@gasmarketing.co.za</a></td><td align="right"><span style="font-size:10px;color:rgba(255,255,255,0.22);">${todayStr()}</span></td></tr></table></td></tr>
</table></td></tr></table></body></html>`;
}

function buildTikTokClientSection(tiktok, combined, readText) {
  const tt = tiktok.total;
  return `<tr><td style="background:#f0f6fb;border-bottom:1px solid #d8e6ef;padding:36px 44px 32px;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:0 0 22px;"><tr><td style="background:#252538;padding:14px 24px;border-radius:8px;"><span style="font-size:14px;font-weight:800;color:#fff;font-family:${F};">TikTok &nbsp;&middot;&nbsp; Campaign Performance</span></td></tr></table><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#1e1e2e;border:1px solid #3a3a4e;border-radius:10px;margin-bottom:18px;"><tr><td style="padding:22px;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0"><tr valign="top"><td width="24%" style="border-right:1px solid #3a3a4e;padding-right:12px;"><p style="margin:0 0 2px;font-size:9px;letter-spacing:2px;text-transform:uppercase;color:#888;font-family:${F};">Impressions</p><p style="margin:0;font-size:22px;font-weight:900;color:#fff;line-height:1;font-family:${F};">${n(tt.impressions)}</p><p style="margin:4px 0 0;font-size:9px;color:#888;">${combined.tiktokShare}% of all</p></td><td width="4%"></td><td width="24%" style="border-right:1px solid #3a3a4e;padding:0 12px;"><p style="margin:0 0 2px;font-size:9px;letter-spacing:2px;text-transform:uppercase;color:#888;font-family:${F};">CPM</p><p style="margin:0;font-size:18px;font-weight:700;color:#4ade80;font-family:${F};">${r(tt.cpm)} Best</p></td><td width="4%"></td><td width="24%" style="padding-left:12px;"><p style="margin:0 0 2px;font-size:9px;letter-spacing:2px;text-transform:uppercase;color:#888;font-family:${F};">Follows / CPF</p><p style="margin:0;font-size:18px;font-weight:900;color:#4ade80;font-family:${F};">${n(tiktok.follower.follows)}</p><p style="margin:4px 0 0;font-size:16px;font-weight:700;color:#fff;font-family:${F};">${r(tiktok.follower.cpf)}</p></td></tr></table></td></tr></table><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#f0f6fb;border-left:4px solid #004F71;border-radius:0 8px 8px 0;margin-top:16px;"><tr><td style="padding:14px 18px;"><p style="margin:0 0 5px;font-size:11px;font-weight:800;color:#004F71;font-family:${F};">TikTok Campaign Read</p><p style="margin:0;font-size:13px;color:#2d2d2d;line-height:1.78;font-family:${F};">${readText}</p></td></tr></table></td></tr>`;
}

// ============ INTERNAL EMAIL ============

function buildInternalEmail(data, narratives) {
  const { meta, tiktok, hasTikTok, combined, community, dateRange } = data;
  const daysLeft = combined.totalDays - combined.daysElapsed;

  const levelColors = { 'HIGH': '#E8231A', 'MEDIUM': '#d4930d', 'WATCH': '#FFCB05' };
  const flagCards = (narratives.flags||[]).map(f => {
    const c = levelColors[f.level]||'#FFCB05';
    return `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin-bottom:10px;border:1px solid rgba(255,255,255,0.15);border-radius:8px;border-left:4px solid ${c};"><tr><td style="padding:14px 18px;"><p style="margin:0 0 4px;font-size:10px;font-weight:700;color:${c};">${f.code} ${f.level}</p><p style="margin:0;font-size:13px;color:rgba(255,255,255,0.90);line-height:1.7;">${f.body}</p></td></tr></table>`;
  }).join('');

  const optRows = (narratives.optimisations||[]).map((o,i) => {
    const bg = i%2===0?'#f0f6fb':'#fff';
    return `<tr bgcolor="${bg}"><td style="padding:10px 12px;font-size:11px;font-weight:700;color:#E8231A;border:1px solid #d8e6ef;">${o.code}</td><td style="padding:10px 12px;font-size:11px;color:#2d2d2d;border:1px solid #d8e6ef;">${o.action}</td><td style="padding:10px 12px;font-size:11px;color:#1a7a3a;font-weight:600;border:1px solid #d8e6ef;">${o.impact}</td></tr>`;
  }).join('');

  const ttInternal = hasTikTok ? `<tr><td style="background:#fff;border-bottom:1px solid #d8e6ef;padding:36px 44px 32px;"><p style="margin:0 0 16px;font-size:10px;font-weight:800;letter-spacing:4px;text-transform:uppercase;color:#004F71;border-left:4px solid #252538;padding-left:12px;font-family:${F};">TikTok Performance</p><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#1e1e2e;border:1px solid #3a3a4e;border-radius:10px;margin-bottom:16px;"><tr><td style="padding:18px;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0"><tr valign="top"><td style="text-align:center;padding:4px 8px;border-right:1px solid #3a3a4e;"><p style="margin:0;font-size:9px;letter-spacing:1px;text-transform:uppercase;color:#888;">Impressions</p><p style="margin:2px 0 0;font-size:18px;font-weight:900;color:#fff;">${n(tiktok.total.impressions)}</p></td><td style="text-align:center;padding:4px 8px;border-right:1px solid #3a3a4e;"><p style="margin:0;font-size:9px;letter-spacing:1px;text-transform:uppercase;color:#888;">CPM</p><p style="margin:2px 0 0;font-size:18px;font-weight:900;color:#4ade80;">${r(tiktok.total.cpm)}</p></td><td style="text-align:center;padding:4px 8px;border-right:1px solid #3a3a4e;"><p style="margin:0;font-size:9px;letter-spacing:1px;text-transform:uppercase;color:#888;">App Install Clicks</p><p style="margin:2px 0 0;font-size:18px;font-weight:900;color:#fff;">${n(tiktok.appInstall.clicks)}</p></td><td style="text-align:center;padding:4px 8px;"><p style="margin:0;font-size:9px;letter-spacing:1px;text-transform:uppercase;color:#888;">Follows</p><p style="margin:2px 0 0;font-size:18px;font-weight:900;color:#4ade80;">${n(tiktok.follower.follows)}</p></td></tr></table></td></tr></table><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#f0f6fb;border-left:4px solid #004F71;border-radius:0 8px 8px 0;"><tr><td style="padding:14px 18px;"><p style="margin:0 0 5px;font-size:11px;font-weight:800;color:#004F71;font-family:${F};">TikTok Insight</p><p style="margin:0;font-size:13px;color:#2d2d2d;line-height:1.78;font-family:${F};">${narratives.tiktokInsight}</p></td></tr></table></td></tr>` : '';

  return `<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/></head>
<body style="margin:0;padding:0;background-color:#e8eff4;"><table role="presentation" border="0" cellpadding="0" cellspacing="0" width="100%" style="background-color:#e8eff4;"><tr><td align="center" style="padding:28px 16px 48px;"><table role="presentation" border="0" cellpadding="0" cellspacing="0" width="700" style="max-width:700px;width:100%;background-color:#fff;border-radius:12px;overflow:hidden;border:1px solid #d8e6ef;">
<tr><td style="background:#fff;padding:14px 32px;border-bottom:1px solid #e8e8e8;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td><span style="display:inline-block;width:30px;height:30px;background:linear-gradient(135deg,#E8231A,#FF7A00);border-radius:50%;text-align:center;line-height:30px;font-size:10px;font-weight:900;color:#fff;vertical-align:middle;font-family:${F};">GAS</span><span style="font-size:11px;font-weight:700;color:#1a1a1a;letter-spacing:1.5px;text-transform:uppercase;vertical-align:middle;margin-left:10px;font-family:${F};">GAS Marketing Automation</span></td><td align="right"><span style="font-size:9px;color:#E8231A;letter-spacing:2px;text-transform:uppercase;font-weight:700;font-family:${F};">Internal &middot; Do Not Forward</span></td></tr></table></td></tr>
<tr><td style="background:#E8231A;padding:6px 32px;"><p style="margin:0;font-size:10px;font-weight:700;letter-spacing:3px;text-transform:uppercase;color:#fff;text-align:center;font-family:${F};">Confidential: Internal Briefing Only</p></td></tr>
<tr><td style="background:linear-gradient(135deg,#002a3d,#004F71);padding:48px 44px 40px;"><p style="margin:0 0 10px;font-size:10px;font-weight:700;letter-spacing:5px;text-transform:uppercase;color:#E8231A;font-family:${F};">Daily Media Insights and Flags &middot; ${monthYear()}</p><h1 style="margin:0 0 4px;font-size:44px;font-weight:900;color:#FFCB05;line-height:1;letter-spacing:-2px;font-family:${F};">MTN MoMo</h1><p style="margin:0;font-size:16px;font-weight:300;color:rgba(255,255,255,0.65);font-family:${F};">${dateRange.from} to ${dateRange.to} &middot; Combined Spend: ${r0(combined.spend)} of ${r0(combined.budget)}</p></td></tr>
<tr><td style="background:linear-gradient(90deg,#E8231A,#FFCB05,#004F71);height:4px;font-size:1px;line-height:1px;">&nbsp;</td></tr>
<tr><td style="background:#f0f6fb;border-bottom:1px solid #d8e6ef;padding:36px 44px 32px;"><p style="margin:0 0 16px;font-size:10px;font-weight:800;letter-spacing:4px;text-transform:uppercase;color:#004F71;border-left:4px solid #1877F2;padding-left:12px;font-family:${F};">Meta KPI Results with Verdicts</p><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#f0f6fb;border-left:4px solid #004F71;border-radius:0 8px 8px 0;"><tr><td style="padding:14px 18px;"><p style="margin:0 0 5px;font-size:11px;font-weight:800;color:#004F71;font-family:${F};">Meta Insight</p><p style="margin:0;font-size:13px;color:#2d2d2d;line-height:1.78;font-family:${F};">${narratives.metaInsight}</p></td></tr></table></td></tr>
${ttInternal}
<tr><td style="background:#004F71;padding:40px 44px;"><p style="margin:0 0 20px;font-size:10px;font-weight:800;letter-spacing:4px;text-transform:uppercase;color:rgba(255,255,255,0.50);font-family:${F};">Flags &nbsp;&middot;&nbsp; ${dateRange.from} to ${dateRange.to}</p>${flagCards}</td></tr>
<tr><td style="background:#fff;border-bottom:1px solid #d8e6ef;padding:36px 44px 32px;"><p style="margin:0 0 16px;font-size:10px;font-weight:800;letter-spacing:4px;text-transform:uppercase;color:#004F71;border-left:4px solid #E8231A;padding-left:12px;font-family:${F};">Optimisation Recommendations</p><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="1" style="border-collapse:collapse;border-color:#d8e6ef;"><thead><tr><th style="padding:10px 12px;font-size:9px;font-weight:700;text-transform:uppercase;color:#FFCB05;text-align:left;border:1px solid #003a55;background:#004F71;">Code</th><th style="padding:10px 12px;font-size:9px;font-weight:700;text-transform:uppercase;color:#FFCB05;text-align:left;border:1px solid #003a55;background:#004F71;">Action</th><th style="padding:10px 12px;font-size:9px;font-weight:700;text-transform:uppercase;color:#FFCB05;text-align:left;border:1px solid #003a55;background:#004F71;">Impact</th></tr></thead><tbody>${optRows}</tbody></table></td></tr>
<tr><td style="background:#fff;border-top:5px solid #FFCB05;padding:36px 44px 32px;"><p style="margin:0;font-size:14px;color:#1a1a1a;line-height:1.9;">Kind regards,<br/><strong style="color:#004F71;">SAMI</strong><br/><span style="font-size:12px;color:#555;">Head of AI Agents Team</span><br/><span style="font-size:12px;color:#555;">GAS Marketing Automation</span></p></td></tr>
<tr><td style="background:linear-gradient(135deg,#E8231A,#FF7A00);border-radius:0 0 12px 12px;padding:20px 44px;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td><span style="font-size:11px;color:rgba(255,255,255,0.80);">GAS Marketing Automation &nbsp;|&nbsp; Digital Performance Team &nbsp;|&nbsp;</span><a href="mailto:grow@gasmarketing.co.za" style="font-size:11px;color:#fff;text-decoration:none;">grow@gasmarketing.co.za</a></td><td align="right"><span style="font-size:10px;color:rgba(255,255,255,0.50);">${todayStr()}</span></td></tr></table></td></tr>
</table></td></tr></table></body></html>`;
}

module.exports = { buildClientEmail, buildInternalEmail };
